// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvxasdrvaycxlvuugwcn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2eGFzZHJ2YXljeGx2dXVnd2NuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MzUyODksImV4cCI6MjA1ODQxMTI4OX0.Dck1he1DCqS8GXNwZr5UqHbbaelxxQ-6eejMEykhdm4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);